name: IAM Workflow
on:
  workflow_dispatch:
    inputs:
      group_email:
        description: 'Adresa de email a grupului'
        required: true
        default: ''
      user_email:
        description: 'Adresa de email a utilizatorului'
        required: true
        default: ''
      service_account_email:
        description: 'Adresa de email a contului de serviciu'
        required: true
        default: ''

jobs:
  update-iam-roles:
    name: Update IAM Roles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Read input variables
        run: |
          echo "group_email: ${{ inputs.group_email }}"
          echo "user_email: ${{ inputs.user_email }}"
          echo "service_account_email: ${{ inputs.service_account_email }}"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="group_email=${{ inputs.group_email }}" -var="user_email=${{ inputs.user_email }}" -var="service_account_email=${{ inputs.service_account_email }}"
