name: IAM Workflow
on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'Project ID'
        required: true
        default: ''
      service_account_id:
        description: 'Service Account ID'
        required: true
        default: ''
      service_account_display_name:
        description: 'Service Account Display Name'
        required: true
        default: ''
      service_account_role:
        description: 'Service Account Role'
        required: true
        default: ''
      create_key:
        description: 'Create Service Account Key'
        required: false
        default: 'false'
      key_created_date:
        description: 'Key Created Date'
        required: false
        default: ${{ strftime('%Y-%m-%d', github.event.created_at) }}

jobs:
  update-iam-roles:
    name: Update IAM Roles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Read input variables
        run: |
          echo "project_id: ${{ inputs.project_id }}"
          echo "service_account_id: ${{ inputs.service_account_id }}"
          echo "service_account_display_name: ${{ inputs.service_account_display_name }}"
          echo "service_account_role: ${{ inputs.service_account_role }}"
          echo "create_key: ${{ inputs.create_key }}"
          echo "key_created_date: ${{ inputs.key_created_date }}"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ inputs.project_id }}" \
            -var="service_account_id=${{ inputs.service_account_id }}" \
            -var="service_account_display_name=${{ inputs.service_account_display_name }}" \
            -var="service_account_role=${{ inputs.service_account_role }}" \
            -var="key_created_date=${{ inputs.key_created_date }}"

      - name: Create Service Account Key
        run: |
          if [[ "${{ inputs.create_key }}" == "true" ]]; then
            gcloud iam service-accounts keys create \
              --iam-account="${{ inputs.service_account_id }}" \
              --key-file-type=json \
              --key-file="${{ inputs.key_created_date }}.json"
          fi
