name: IAM Workflow
on:
  workflow_dispatch:
    inputs:
      service_account_id:
        description: 'Service Account ID'
        required: true
        default: ''
      service_account_display_name:
        description: 'Service Account Display Name'
        required: true
        default: ''
      service_account_role:
        description: 'Service Account Role'
        required: true
        default: ''

jobs:
  iam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Read input variables
        run: |
          echo "service_account_id: ${{ inputs.service_account_id }}"
          echo "service_account_display_name: ${{ inputs.service_account_display_name }}"
          echo "service_account_role: ${{ inputs.service_account_role }}"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="service_account_id=${{ inputs.service_account_id }}" -var="service_account_display_name=${{ inputs.service_account_display_name }}" -var="service_account_role=${{ inputs.service_account_role }}"
