name: IAM Workflow

on:
  workflow_dispatch:
    inputs:
      service_account_id:
        description: 'Service Account ID'
        required: true
        default: ''
      service_account_display_name:
        description: 'Service Account Display Name'
        required: true
        default: ''
      service_account_role:
        description: 'Service Account Role'
        required: true
        default: ''
      create_key:
        description: 'Create Service Account Key'
        required: true
        default: 'true'

jobs:
  update-iam-roles:
    name: Update IAM Roles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Read input variables
        run: |
          echo "service_account_id: ${{ github.event.inputs.service_account_id }}"
          echo "service_account_display_name: ${{ github.event.inputs.service_account_display_name }}"
          echo "service_account_role: ${{ github.event.inputs.service_account_role }}"
          echo "create_key: ${{ github.event.inputs.create_key }}"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="service_account_id=${{ github.event.inputs.service_account_id }}" \
            -var="service_account_display_name=${{ github.event.inputs.service_account_display_name }}" \
            -var="service_account_role=${{ github.event.inputs.service_account_role }}" \
            -var="create_key=${{ github.event.inputs.create_key }}"

      - name: Read service account key created time
        id: read-key-created-time
        run: echo "::set-output name=key_created_time::$(terraform output -raw service_account_key_created_time)"

      - name: Create Service Account Key
        run: |
          if [[ "${{ github.event.inputs.create_key }}" == "true" ]]; then
            gcloud iam service-accounts keys create \
              --iam-account="${{ github.event.inputs.service_account_id }}" \
              --key-file-type=json
          fi
